# Generated by Django 6.0.3 on 2026-03-21 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
